### ISSUE TITLE
Your Quickstart does not even work

### ISSUE THREAD

**Issue by gitricko** [pomerium/documentation#65]
Page:https://github.com/pomerium/documentation/blob/main/content/docs/install/quickstart.mdx

## What's incorrect or missing

Follow it and uses the simple github IDP

## What's the resolution?

Better documentation. The route does not make sense. Either that or we need instruction for github call back URL.. where it should throw the UI to ?

I think authelia does a better job on configuration.

**Comment by alexfornuto** [comment]
Hi @gitricko. I'd like to help you out here, but we'd need more details on where you ran into problems. Please note that the specific instructions for each IdP Pomerium supports are listed under **Identity Providers**. If you're using GitHub, see https://www.pomerium.com/docs/identity-providers/github

**Comment by gitricko** [comment]
Thanks, and yes it turns out i missed our configuration in github idp.

After the redirect came back to verify, i got this error.
![Screen Shot 2022-07-11 at 1 05 45 PM](https://user-images.githubusercontent.com/18060558/178348894-04fa3ba1-a988-4fb9-a774-31eb610370a7.png)

Look at this closely, i notice that my API of https://authenticate.pomerium.uncletechno.com/.well-known/pomerium/jwks.json
returns
```
{"keys":null}
```

Not is sure what is wrong now..

I can comment more how to improve the docu

**Comment by alexfornuto** [comment]
Sorry for the delayed response.

Regarding the numerical "improvements needed":

1. GitHub would not be a good choice for a default IdP because we're targeting business, and GitHub is not a popular IdP for business use. The first line of the Prerequisites section says you already need a configured IdP and links to the list so you can choose the appropriate documentation.
2. If you don't know anything about SSL, you're probably not in a great position to be using Pomerium. I've always strived to make any docs I write be as user-friendly as possible, but certain prerequisite knowledge has to be assumed at some point, as long as it is specified. And it is, in third bullet under Prerequisites, which also links to our guide on TLS.
  Regarding Docker, if you're not comfortable with Docker you should use the Binary method to test the product. Or the Kubernetes method, if that's something you're already familiar with.
3. You can find network diagrams [here](https://www.pomerium.com/docs/overview/architecture) and [here](https://www.pomerium.com/docs/topics/mutual-auth)

As for `signing_key` and `signing_key_algorithm`, those should not be required with v17 or higher and without also using Pomerium Enterprise. We'll look into it further.
